#!/usr/bin/env python
from __future__ import print_function

import argparse
import json
from gca.core import Session
from gca.auth import NetRCAuth


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='GCA Client')
    parser.add_argument('url', type=str)
    subparsers = parser.add_subparsers(help='commands')

    parser_abs = subparsers.add_parser("abstracts", help='list abstracts')
    parser_abs.add_argument('conference', type=str, help='for which conference')
    parser_abs.set_defaults(cmd='abstracts')

    args = parser.parse_args()

    auth = NetRCAuth()
    session = Session(args.url, auth)

    if args.cmd == 'abstracts':
        abstracts = session.get_all_abstracts(args.conference, raw=True)
        print(json.dumps(abstracts, sort_keys=True, indent=4, separators=(',', ': ')))
