#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function
from __future__ import unicode_literals

import argparse
import codecs
import sys

from gca.core import Abstract

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='GCA doi - generate DOIs for abstracts')
    parser.add_argument('file', type=str, default='-')
    parser.add_argument('prefix', type=str)
    args = parser.parse_args()

    fd = codecs.open(args.file, 'r', encoding='utf-8') if args.file != '-' else sys.stdin
    abstracts = Abstract.from_data(fd.read())
    for idx, a in enumerate(abstracts):
        a.doi = "%s%04d" % (args.prefix, idx+1)
    data = Abstract.to_json(abstracts)
    sys.stdout.write(data.encode('utf-8'))